version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  jobs:
    pre_install:
      # Install uv
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.cargo/bin:$PATH"

      # Install dependencies into .venv using uv
      - uv python install 3.13
      - uv sync --frozen

      # Activate the venv so sphinx runs in it
      - eval "$(uv venv activate --env .venv)"

sphinx:
  configuration: docs/conf.py